repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: '(migrations|.cache)/'
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["-j8", "--ignore=E402, E203"]
        additional_dependencies:
          [flake8-comprehensions>=3.2.2, flake8-builtins>=1.5.2]