POST http://localhost:8000/api/v1/test/ HTTP/1.1
Content-Type: application/json
Authorization: Token ee544e3431123548961bb108e66aa6af75e87bb2

{
    "title": "Test",
    "description": "Test description",
    "category": "Test category",
    "params": {
        "model": {
            "model_type": "LSTM",
            "model_params": {
                "hidden_size": 128,
                "num_layers": 2,
                "dropout": 0.2,
                "batch_size": 64,
                "num_epochs": 10,
                "learning_rate": 0.001
            }
        }
    },
    "attachment_id": 1
}
